account_id = "388646735826"
region = "us-east-1"

[vpc]
n_azs = 2

[dns]
home_domain_name = "aaronmamparo.com"

[billing_alert]
email = "aaronmamparo@gmail.com"
estimated_monthly_charges_threshold_usd = 50